version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      # Install dependencies
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install mlflow boto3 pandas

  build:
    commands:
      # Run MLflow server or any build steps you need
      - echo Running MLflow project...
      - mlflow run .

  post_build:
    commands:
      # Optionally, you can add any post-build steps here
      - echo "Post-build step completed."

artifacts:
  files:
    - '*/'
    - 'mlflow.db'  # Include any artifacts or files you want to store in S3
    - 'mlruns/*/'  # Save MLflow run logs or output if needed
  discard-paths: no  # Retain directory structure for S3 upload
